# 2019 Country Happiness Score - Linear Regression
## by Maxwell Grant

Database: World Happiness Report 2019

Link: https://www.kaggle.com/PromptCloudHQ/world-happiness-report-2019

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

Read the csv file to a dataframe.

In [2]:
df = pd.read_csv('happy2019.csv')

In [3]:
df.head(3)

,Overall rank,Country,Region,Latitude,Longitude,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,46.2022,1.2644,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,Western Europe,46.2022,1.2644,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,Western Europe,46.2022,1.2644,7.554,1.488,1.582,1.028,0.603,0.271,0.341

In [4]:
df.columns.values

array(['Overall rank', 'Country', 'Region', 'Latitude', 'Longitude',
       'Score', 'GDP per capita', 'Social support',
       'Healthy life expectancy', 'Freedom to make life choices',
       'Generosity', 'Perceptions of corruption'], dtype=object)

Prepare the data to be tested. Drop columns not required. Separate x-variables and the y-variable.

In [5]:
Drop = ['Overall rank', 'Country', 'Region', 'Latitude', 'Longitude']
dfEvaluate = df.drop(Drop,axis=1)
X = dfEvaluate.drop('Score',axis=1)    # Predictors/Input Variables/DV
y = dfEvaluate['Score']    # Target/Label/IV

Split the data into training and testing data set. This model tests with 60% training and 40% testing.

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6, random_state=101)

Initiate model and feed training data

In [7]:
bhr_model = LinearRegression() 
bhr_model.fit(X_train,y_train)

LinearRegression()

In [8]:
test_predictions = bhr_model.predict(X_test)

Series of variable coefficients.

In [9]:
df_bhr_coeff = pd.DataFrame(bhr_model.coef_,X.columns,columns=['Coefficient'])
df_bhr_coeff

                              Coefficient
GDP per capita                   0.517708
Social support                   1.724451
Healthy life expectancy          1.559098
Freedom to make life choices     1.215421
Generosity                       2.079074
Perceptions of corruption        0.476912

Create a list of evaluation metrics for the linear regression.

In [10]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)
R_SQR = r2_score(y_test, test_predictions)
yINT = bhr_model.intercept_
printDict = {MAE: 'Mean Absolute Error: ', MSE:'Mean Squared Error: ',
             RMSE:'Square Root Mean Squared Error: ', R_SQR: 'R^2: ', 
             yINT:'Y-Intercept: '}
printList = [MAE,MSE,RMSE,R_SQR,yINT]

Evaluation: This model is a good fit with a r^2 of 61%. In the domain of human analytics, 61% is a high score.

In [11]:
for item in printList:
    print(printDict.get(item), round(item, 2))

Mean Absolute Error:  0.47
Mean Squared Error:  0.37
Square Root Mean Squared Error:  0.61
R^2:  0.64
Y-Intercept:  0.72